### ISSUE TITLE
No car.png

### ISSUE THREAD

**Issue by iliakonnov** [LiamRahav/cocos2d-python-tutorials#4]
```
python add.py 
Traceback (most recent call last):
  File "add.py", line 83, in <module>
    car_layer = CarLayer()
  File "add.py", line 65, in __init__
    self.sprite = Sprite("assets/img/car.png")
  File "/usr/local/lib/python2.7/dist-packages/cocos/sprite.py", line 121, in __init__
    image = pyglet.resource.image(image)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/resource.py", line 529, in image
    atlas=atlas)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/resource.py", line 458, in _alloc_image
    file = self.file(name)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/resource.py", line 414, in file
    raise ResourceNotFoundException(name)
pyglet.resource.ResourceNotFoundException: Resource "assets/img/car.png" was not found on the path.  Ensure that the filename has the correct captialisation.
```

Link to car.png that I found: https://github.com/adamwiggins/cocos2d/blob/master/test/car.png

**Comment by liamrahav** [comment]
Fixed this in pull req #5, thanks for pointing it out
