### ISSUE TITLE
SDL Error in basics/audio.py

### ISSUE THREAD

**Issue by dperrocco** [LiamRahav/cocos2d-python-tutorials#9]
Hi there,
I'm running into a problem in the audio tutorial, where it seems I'm getting an SDL error. I'm running it in a venv with python3.6, and cocos2d 0.6.5, on a Debian OS. To be sure I wasn't typing something in incorrectly, I've copied and pasted the tutorial over, to no avail. Is this anything you've seen with a simple solution? Apologies if it's something stupid I've overlooked!

I have a traceback here:
```Traceback (most recent call last):
  File "cocos2d-testing/basics/audio.py", line 38, in <module>
    director.run(scene.Scene(AudioLayer()))
  File "cocos2d-testing/basics/audio.py", line 27, in __init__
    song = Audio("assets/sound/LatinIndustries.ogg")
  File "cocos2d-testing/basics/audio.py", line 19, in __init__
    super(Audio, self).__init__(audio_file)
  File "/path/to/.venvs/cocos2d-testing/lib/python3.6/site-packages/cocos/audio/pygame/mixer.py", line 423, in __init__
    self._chunk = Mix_LoadWAV(file)
  File "/path/to/.venvs/cocos2d-testing/lib/python3.6/site-packages/cocos/audio/SDL/mixer.py", line 156, in Mix_LoadWAV
    return Mix_LoadWAV_RW(rwops.SDL_RWFromFile(filename, b'rb'), 1)
  File "/path/to/.venvs/cocos2d-testing/lib/python3.6/site-packages/cocos/audio/SDL/dll.py", line 210, in _f
    raise cocos.audio.SDL.error.SDL_Exception(cocos.audio.SDL.error.SDL_GetError())
cocos.audio.SDL.error.SDL_Exception: <exception str() failed>
Exception ignored in: <bound method Sound.__del__ of <__main__.Audio object at 0x7f69189ed308>>
Traceback (most recent call last):
  File "/path/to/.venvs/cocos2d-testing/lib/python3.6/site-packages/cocos/audio/pygame/mixer.py", line 426, in __del__
    if self._chunk:
AttributeError: _chunk
```

**Comment by dperrocco** [comment]
Okay, I see you're no longer working on this project. Hopefully someone will know what's up?

**Comment by dperrocco** [comment]
I've found the solution. Since Python opens files relative to the working directory, it would only open if the working directory was the basics folder.

To access the audio file regardless of working directory, I changed
`song = Audio("assets/sound/LatinIndustries.ogg")`
to
`song = Audio(os.path.abspath(__file__ + "/../assets/sound/LatinIndustries.ogg"))`

Obviously this necessitates a new import.
